/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import javax.swing.Icon;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author mrtru
 */
public class Chat_left_with_profile extends javax.swing.JLayeredPane {

    /**
     * Creates new form Chat_left
     */
    public Chat_left_with_profile() {
        initComponents();
        setLayout(new MigLayout("fillx, insets 0", "[32px][grow]", "[bottom]"));
        txt.setBackground(new Color(229,229,229));
    }
    public void setUserProfile(String user){
        txt.setUserProfile(user);
    }
    
    public void setImageProfile(Icon image){
        IAimage.setImage(image);
    }
    
    public void setImage(Icon... image) {
      //  txt.setImage(false, image);
    }

    public void setImage(String... image) {
        //txt.setImage(false, image);
    }
    public void setText(String text){
        if (text.equals("")) {
            txt.hideText();
        } else {
            txt.setText(text);
        }
    }
    public void setFile(String filename,String filesize){
        txt.setFile(filename, filesize);
    }
    public void setTime() {
        txt.setTime("10:30 PM");    //  Testing
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        IAimage = new swing.ImageAvatar();
        txt = new component.Chat_Item();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        IAimage.setBorderSize(0);
        IAimage.setImage(new javax.swing.ImageIcon(getClass().getResource("/icon/test/avatar.png"))); // NOI18N
        IAimage.setMaximumSize(new java.awt.Dimension(32, 32));
        IAimage.setMinimumSize(new java.awt.Dimension(32, 32));
        IAimage.setName(""); // NOI18N
        IAimage.setPreferredSize(new java.awt.Dimension(32, 32));

        jLayeredPane1.setLayer(IAimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IAimage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IAimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jLayeredPane1);
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ImageAvatar IAimage;
    private javax.swing.JLayeredPane jLayeredPane1;
    private component.Chat_Item txt;
    // End of variables declaration//GEN-END:variables
}
