/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Service.Service;
import event.EventFileReceiver;
import event.EventFileSender;
import java.io.File;
import java.io.IOException;
import model.Model_File_Sender;
import model.Model_Receive_File;

/**
 *
 * @author mrtru
 */
public class Chat_File extends javax.swing.JPanel {

    /**
     * Creates new form Chat_file
     */
    public Chat_File() {
        initComponents();
        setOpaque(false);
    }

    public void setFile(Model_File_Sender fileSender) {
        lbFileName.setText(fileSender.getFile().getName());
        String readsize = formatFileSize(fileSender.getFileSize());
        lbFileSize.setText(readsize);
        fileSender.addEvent(new EventFileSender(){
            @Override
            public void onSending(double percentage) {

                progress.setValue((int) percentage);
            }

            @Override
            public void onStartSending() {
            }

            @Override
            public void onFinish() {
                progress.setValue(0);
            }


        });
    }
    public void setFile(Model_Receive_File dataFile) {
        try {
            
            Service.getInstance().addFileReceiver(dataFile.getFileID(), new EventFileReceiver() {
                @Override
                public void onReceiving(double percentage) {
//                    lbFileName.setText(String.valueOf(dataFile.getFileID()));
                }

                @Override
                public void onStartReceiving(long filesize,String filename,String fileExtension) {
                    String readsize = formatFileSize(filesize);
                    lbFileName.setText(filename + fileExtension);
                    lbFileSize.setText(readsize);
                }

                @Override
                public void onFinish(File file) {
                    progress.setValue(0);

                }
            });
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private String formatFileSize(long size) {
        if (size < 1024) {
            return size + " B";
        } else if (size < 1024 * 1024) {
            return String.format("%.2f KB", size / 1024.0);
        } else if (size < 1024 * 1024 * 1024) {
            return String.format("%.2f MB", size / (1024.0 * 1024));
        } else {
            return String.format("%.2f GB", size / (1024.0 * 1024 * 1024));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbFileName = new javax.swing.JLabel();
        lbFileSize = new javax.swing.JLabel();
        progress = new swing.Progress();

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        lbFileName.setText("My File Name.file");
        jPanel1.add(lbFileName);

        lbFileSize.setForeground(new java.awt.Color(51, 102, 255));
        lbFileSize.setText("5mb");
        jPanel1.add(lbFileSize);

        progress.setProgresstype(swing.Progress.ProgressType.FILE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFileName;
    private javax.swing.JLabel lbFileSize;
    private swing.Progress progress;
    // End of variables declaration//GEN-END:variables
}
